version: '3'
services:
  wordpress:
    image: visiblevc/wordpress:latest
    ports:
      - 8080:80
    volumes:
      - ./data:/data
      - ./wp-content/uploads:/app/wp-content/uploads
    # - ./plugins/MY_PLUGIN:/app/wp-content/plugins/MY_PLUGIN # Plugin development
    # - ./themes/MY_THEME:/app/wp-content/themes/MY_THEME   # Theme development
    environment:
      DB_HOST: db
      DB_NAME: wordpress
      DB_PASS: 27DLZd5uckTg2J23
    # PLUGINS: >-
    #   custom-post-type-ui,
    #   advanced-custom-fields,
    #   woocommerce,
      URL_REPLACE: yoursite.com,localhost:8080
      WP_DEBUG: 'true'
  db:
    image: mysql:5.7
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 27DLZd5uckTg2J23
volumes:
  data: {}